export const HOME_1 = "HOME_1";
export const GET_BLOG = "GET_BLOG";
export const GET_MAS_BLOG = "GET_MAS_BLOG";
export const GET_SINGLE_BLOG = "GET_SINGLE_BLOG";
export const NEXT_POST = "NEXT_POST";
export const PREV_POST = "PREV_POST";
export const HOME_2 = "HOME_2";
export const HOME_3 = "HOME_3";
export const HOME_4 = "HOME_4";
export const HOME_5 = "HOME_5";
export const BRAND = "BRAND";
export const TESTIMONIAL = "TESTIMONIAL";
export const CATEGORY_1 = "CATEGORY_1";
export const CATEGORY_2 = "CATEGORY_2";
export const CATEGORY_3 = "CATEGORY_3";

// Product
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_SINGLE = "GET_SINGLE";
export const GET_PRODUCT_RECOMMENDED = "GET_PRODUCT_RECOMMENDED";
export const GET_PRODUCT_FLASH_SELL = "GET_PRODUCT_FLASH_SELL";
export const GET_PRODUCT_MOST_PURCHASE = "GET_PRODUCT_MOST_PURCHASE";

// filter
export const FILTER_NAME = "FILTER_NAME";
export const FILTER_BRAND = "FILTER_BRAND";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
export const FILTER_SIZE = "FILTER_SIZE";
export const FILTER_PRICE = "FILTER_PRICE";
export const FILTER_COLOR = "FILTER_COLOR";
export const FILTER_TAG = "FILTER_TAG";

// Utiles
export const GET_CARTS = "GET_CARTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART = "REMOVE_CART";
export const REMOVE_CART_ALL = "REMOVE_CART_ALL";
export const DECREASE_CART = "DECREASE_CART";
export const CART_AMOUNT = "CART_AMOUNT";
export const COMPARE = "COMPARE";
export const GET_COMPARE = "GET_COMPARE";
export const REMOVE_COMPARE = "REMOVE_COMPARE";
export const QUICK_VIEW = "QUICK_VIEW";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const GET_WISHLIST = "GET_WISHLIST";

export const CHECKOUT_USER = "CHECKOUT_USER";

//Authentication
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const REGISTER_REQUEST= "REGISTER_REQUEST";
export const REGISTER_FAILURE= "REGISTER_FAILURE";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";

export const ADD_ORDER_REQUEST= "ADD_ORDER_REQUEST";
export const ADD_ORDER_SUCCESS= "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE= "ADD_ORDER_FAILURE";
export const GET_ORDER_BY_ID_REQUEST= "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS= "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE= "GET_ORDER_BY_ID_FAILURE";
export const GET_ORDER_LASTED= "GET_ORDER_LASTED";

export const RATE_PRODUCT_REQUEST= "RATE_PRODUCT_REQUEST";
export const RATE_PRODUCT_SUCCESS= "RATE_PRODUCT_SUCCESS";
export const RATE_PRODUCT_FAILURE= "RATE_PRODUCT_FAILURE";


export const CUSTOMER_ADDRESS_REQUEST= "CUSTOMER_ADDRESS_REQUEST";
export const CUSTOMER_ADDRESS_SUCCESS= "CUSTOMER_ADDRESS_SUCCESS";
export const CUSTOMER_ADDRESS_FAILURE= "CUSTOMER_ADDRESS_FAILURE";